chore/update-pr-workflow (#187)
* tester ny PR workflow

* fix

* legger til at PR kjøres på nytt når det er edited

* endrer rekkefølge

* endrer workflow navn

* endrer workflow navn

* endrer workflow navn

* legger til feilmelding hvis workflow feiler

diff --git a/.github/workflows/build-pr.yaml b/.github/workflows/build-pr.yaml
--- a/.github/workflows/build-pr.yaml
+++ b/.github/workflows/build-pr.yaml
@@ -1,13 +1,42 @@
-name: Build and PR Labeler
+name: Build/test and validate PR
 
 on:
   pull_request:
+    types: [opened, edited, synchronize]
 
 jobs:
+  validate-pr:
+    name: Validate PR Branch and Title
+    runs-on: ubuntu-latest
+    continue-on-error: true
+    steps:
+      - name: Check out repository
+        uses: actions/checkout@v4
+
+      - name: Validate PR branch name and title
+        run: |
+          BRANCH_NAME=$(echo "${{ github.head_ref }}" | grep -E '^(feature|bugfix|hotfix|chore|refactor|docs)/')
+          PR_TITLE=$(echo "${{ github.event.pull_request.title }}" | grep -E '^(feature|bugfix|hotfix|chore|refactor|docs)/')
+          
+          if [[ -z "$BRANCH_NAME" ]]; then
+            echo "::error::Branch name does not match the required prefixes. Please use one of the following prefixes: feature/*, bugfix/*, hotfix/*, chore/*, refactor/*, docs/*."
+            exit 1
+          fi
+          
+          if [[ -z "$PR_TITLE" ]]; then
+            echo "::error::PR title does not match the required prefixes. Please start the title with one of the following prefixes: feature/*, bugfix/*, hotfix/*, chore/*, refactor/*, docs/*."
+            exit 1
+          fi
+
+      - name: Success message
+        if: success()
+        run: echo "Branch name and PR title are valid."
+
   build-pr:
     name: Build and test
     runs-on: ubuntu-latest
-    if: "!contains(github.event.pull_request.changed_files, 'LICENSE') && !contains(github.event.pull_request.changed_files, 'CODEOWNERS') && !contains(github.event.pull_request.changed_files, '.gitignore') && !contains(github.event.pull_request.changed_files, '.editorconfig') && !contains(github.event.pull_request.changed_files, 'setupLocalEnvironment.sh') && !contains(github.event.pull_request.changed_files, 'dokumentasjon/**') && !contains(github.event.pull_request.changed_files, '.nais/**') && !contains(github.event.pull_request.changed_files, '.github/workflows/deploy.yaml') && !contains(github.event.pull_request.changed_files, '.github/workflows/manual-deploy-dev.yaml') && !contains(github.event.pull_request.changed_files, '.github/workflows/security.yaml') && !contains(github.event.pull_request.changed_files, '.github/workflows/alerts.yaml')"
+    needs: validate-pr
+    if: "!failure() && !contains(github.event.pull_request.changed_files, 'LICENSE') && !contains(github.event.pull_request.changed_files, 'CODEOWNERS') && !contains(github.event.pull_request.changed_files, '.gitignore') && !contains(github.event.pull_request.changed_files, '.editorconfig') && !contains(github.event.pull_request.changed_files, 'setupLocalEnvironment.sh') && !contains(github.event.pull_request.changed_files, 'dokumentasjon/**') && !contains(github.event.pull_request.changed_files, '.nais/**') && !contains(github.event.pull_request.changed_files, '.github/workflows/deploy.yaml') && !contains(github.event.pull_request.changed_files, '.github/workflows/manual-deploy-dev.yaml') && !contains(github.event.pull_request.changed_files, '.github/workflows/security.yaml') && !contains(github.event.pull_request.changed_files, '.github/workflows/alerts.yaml')"
     steps:
       - uses: actions/checkout@v4
         with:
