teste igjen

diff --git a/.github/workflows/build-pr.yaml b/.github/workflows/build-pr.yaml
--- a/.github/workflows/build-pr.yaml
+++ b/.github/workflows/build-pr.yaml
@@ -1,57 +1,21 @@
-name: Build/test and validate PR
+name: Build/test PR
 
 on:
   pull_request:
-    types: [opened, edited, synchronize]
 
 jobs:
-  validate-pr:
-    name: Validate PR Branch and Title
-    runs-on: ubuntu-latest
-    continue-on-error: true
-    steps:
-      - name: Check out repository
-        uses: actions/checkout@v4
-
-      - name: Validate PR branch name and title
-        id: validate
-        run: |
-          BRANCH_NAME=$(echo "${{ github.head_ref }}" | grep -E '^(feature|bugfix|hotfix|chore|refactor|docs)/')
-          PR_TITLE=$(echo "${{ github.event.pull_request.title }}" | grep -E '^(feature|bugfix|hotfix|chore|refactor|docs)/')
-          
-          if [[ -z "$BRANCH_NAME" ]]; then
-            echo "::error::Branch name does not match the required prefixes. Please use one of the following prefixes: feature/*, bugfix/*, hotfix/*, chore/*, refactor/*, docs/*."
-            echo "error_message=Branch name does not match the required prefixes." >> $GITHUB_ENV
-            echo "branch_error=1" >> $GITHUB_ENV
-          fi
-          
-          if [[ -z "$PR_TITLE" ]]; then
-            echo "::error::PR title does not match the required prefixes. Please start the title with one of the following prefixes: feature/*, bugfix/*, hotfix/*, chore/*, refactor/*, docs/*."
-            echo "error_message=PR title does not match the required prefixes." >> $GITHUB_ENV
-            echo "title_error=1" >> $GITHUB_ENV
-          fi
-
-      - name: Success message
-        if: success()
-        run: echo "Branch name and PR title are valid."
-
-      - name: Failure message
-        if: failure()
-        run: |
-          if [[ "${{ env.branch_error }}" == "1" ]]; then
-            echo "Branch name does not match the required prefixes."
-          fi
-          if [[ "${{ env.title_error }}" == "1" ]]; then
-            echo "PR title does not match the required prefixes."
-          fi
-          exit 1
-
   build-pr:
     name: Build and test
     runs-on: ubuntu-latest
-    needs: validate-pr
-    if: ${{ success() }} && !contains(github.event.pull_request.changed_files, 'LICENSE') && !contains(github.event.pull_request.changed_files, 'CODEOWNERS') && !contains(github.event.pull_request.changed_files, '.gitignore') && !contains(github.event.pull_request.changed_files, '.editorconfig') && !contains(github.event.pull_request.changed_files, 'setupLocalEnvironment.sh') && !contains(github.event.pull_request.changed_files, 'dokumentasjon/**') && !contains(github.event.pull_request.changed_files, '.nais/**') && !contains(github.event.pull_request.changed_files, '.github/workflows/deploy.yaml') && !contains(github.event.pull_request.changed_files, '.github/workflows/manual-deploy-dev.yaml') && !contains(github.event.pull_request.changed_files, '.github/workflows/security.yaml') && !contains(github.event.pull_request.changed_files, '.github/workflows/alerts.yaml')
     steps:
+      - name: Check branch name and title
+        run: |
+          BRANCH_NAME=${{ github.head_ref }}
+          PR_TITLE=${{ github.event.pull_request.title }}
+          if [[ ! "$BRANCH_NAME" =~ ^(feature|bugfix|hotfix|chore|refactor|docs)/ ]] || [[ ! "$PR_TITLE" =~ ^(feature|bugfix|hotfix|chore|refactor|docs)/ ]]; then
+            echo "Branch name or PR title does not match the required prefixes."
+            exit 1
+          fi
       - uses: actions/checkout@v4
         with:
           ref: ${{ github.event.pull_request.head.sha }}
